# Generated by Django 6.0.5 on 2026-05-30 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETE', 'Complete'), ('AI_GENERATED', 'AI Generated')], default='DRAFT', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_compatible', models.BooleanField(default=True)),
                ('compatibility_notes', models.TextField(blank=True)),
                ('ai_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('CPU', 'Processor'), ('GPU', 'Graphics Card'), ('RAM', 'Memory'), ('STORAGE', 'Storage'), ('MOTHERBOARD', 'Motherboard'), ('PSU', 'Power Supply'), ('CASE', 'Case'), ('COOLING', 'Cooling')], max_length=20)),
                ('custom_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='builds.build')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_components', to='products.product')),
            ],
            options={
                'unique_together': {('build', 'component_type')},
            },
        ),
    ]
