# Generated by Django 6.0.5 on 2026-06-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerlocation',
            name='name',
            field=models.CharField(default='My Store', max_length=255),
        ),
    ]
